### Create Book
POST localhost:8080/book
Content-Type: application/json

{
  "name": "aaaaaaaaaaaaa",
  "title": "bbbbbbb",
  "publishYear": "2002-08-28"
}

### Get book list
GET localhost:8080/book

### Get book By Id
GET localhost:8080/book/1



### Update book by id
PUT localhost:8080/book/1
Content-Type: application/json

{
  "name": "qolgan",
  "title": "ketgan",
  "publishYear": "2012-10-28"
}

###Delete book by id
DELETE localhost:8080/book/3

###Search book by name and title
GET localhost:8080/book/search?name=e&title=f