### Create Book
POST localhost:8080/book
Content-Type: application/json

{
  "name": "alissaxasadcfgb",
  "title": "bbaaaaaaaaab"
}

### Get book list
GET localhost:8080/book

### Get book By Id
GET localhost:8080/book/6



### Update book by id
PUT localhost:8080/book/6
Content-Type: application/json

{
  "name": "ssssssssss",
  "title": "dddddddddddddd"
}

###Delete book by id
DELETE localhost:8080/book/6

###Search book by name and title
GET localhost:8080/book/search?name=e&title=f