### Create Student
POST localhost:8080/student
Content-Type: application/json

{
  "name": "aaa",
  "surname": "bbb"
}

### Get student list
GET localhost:8080/student

### Get student By Id
GET localhost:8080/student/2c0178e9-8a11-41b2-9ee2-9ef5337f5507

### Update student by id
PUT localhost:8080/student/2c0178e9-8a11-41b2-9ee2-9ef5337f5507
Content-Type: application/json

{
  "name": "aaaa",
  "surname": "bbbb"
}

###Delete student by id
DELETE localhost:8080/student/2c0178e9-8a11-41b2-9ee2-9ef5337f5507

###Search student by name and surname
GET localhost:8080/student/search?name=hu&surname=v