### Create Student
POST localhost:8080/student
Content-Type: application/json

{
  "name": "hasan",
  "surname": "teshayev",
  "phone": "+777",
  "age": 25
}

### Get student list
GET localhost:8080/student

### Get student By Id
GET localhost:8080/student/2
### Update student by id
PUT localhost:8080/student/2
Content-Type: application/json

{
  "name": "ccccccc",
  "surname": "pppppp",
  "phone": "+022",
  "age": 28
}


###Delete student by id
DELETE localhost:8080/student/6

###Search student by name and surname
GET localhost:8080/student/search?name=hasan&surname=v